import type {
  CampaignDefinition,
  JourneyChapter,
} from "../domain/types";

export const techbridgeCampaignChapters: JourneyChapter[] = [
  {
    id: "prologue-choose-destination",
    order: 0,
    title: "Prólogo — Escolher o Destino",
    purpose: "Definir o objetivo",
    missionIds: [],
    checkpointType: "prologue",
    visualStage: "destination",
    required: true,
  },
  {
    id: "chapter-1-light-the-bridge",
    order: 1,
    title: "Capítulo 1 — Acender a Ponte",
    purpose: "Iniciar a travessia",
    missionIds: [],
    checkpointType: "chapter",
    visualStage: "bridge-off",
    required: true,
  },
  {
    id: "chapter-2-find-the-path",
    order: 2,
    title: "Capítulo 2 — Encontrar o Caminho",
    purpose: "Orientar o percurso",
    missionIds: [],
    checkpointType: "chapter",
    visualStage: "path-visible",
    required: true,
  },
  {
    id: "chapter-3-create-connections",
    order: 3,
    title: "Capítulo 3 — Criar Conexões",
    purpose: "Conectar e comunicar",
    missionIds: ["professional-email", "send-attachments"],
    checkpointType: "chapter",
    visualStage: "connections-active",
    required: true,
  },
  {
    id: "chapter-4-digital-shield",
    order: 4,
    title: "Capítulo 4 — Escudo Digital",
    purpose: "Proteger a travessia",
    missionIds: [],
    checkpointType: "chapter",
    visualStage: "shield-active",
    required: true,
  },
  {
    id: "chapter-5-build-and-produce",
    order: 5,
    title: "Capítulo 5 — Construir e Produzir",
    purpose: "Criar entregas úteis",
    missionIds: [],
    checkpointType: "chapter",
    visualStage: "construction-active",
    required: true,
  },
  {
    id: "chapter-6-intelligence-with-purpose",
    order: 6,
    title: "Capítulo 6 — Inteligência com Propósito",
    purpose: "Usar inteligência com intenção",
    missionIds: [],
    checkpointType: "chapter",
    visualStage: "purpose-active",
    required: true,
  },
  {
    id: "chapter-7-goal-in-action",
    order: 7,
    title: "Capítulo 7 — Objetivo em Ação",
    purpose: "Aplicar uma rota",
    missionIds: ["build-first-resume", "review-resume"],
    checkpointType: "route",
    visualStage: "goal-active",
    required: true,
  },
  {
    id: "chapter-8-digital-autonomy",
    order: 8,
    title: "Capítulo 8 — Autonomia Digital",
    purpose: "Consolidar autonomia",
    missionIds: [],
    checkpointType: "campaign-completion",
    visualStage: "city-revealed",
    required: true,
  },
];

export const techbridgeCampaign: CampaignDefinition = {
  id: "techbridge-campaign",
  title: "TechBridge Journey",
  chapters: techbridgeCampaignChapters,
};
